openapi: 3.0.3
info:
  title: Todo Backend Health API
  description: Health check API for the Todo Backend database connection
  version: 1.0.0
servers:
  - url: http://localhost:8000
    description: Development server
paths:
  /health:
    get:
      summary: Health check endpoint
      description: Verifies database connectivity and overall system health
      responses:
        '200':
          description: System is healthy and database connection is established
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    enum: [healthy]
                    description: Current system status
                    example: healthy
                  db_connected:
                    type: boolean
                    description: Whether database connection is established
                    example: true
                required:
                  - status
                  - db_connected
        '503':
          description: Service unavailable due to database connection issues
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    enum: [unhealthy]
                    description: Current system status
                    example: unhealthy
                  error:
                    type: string
                    description: Error message describing the issue
                    example: Database connection failed
                required:
                  - status
                  - error
components:
  schemas: {}